# Generated by Django 3.2.4 on 2022-01-12 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('roll_number', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('department_name', models.CharField(blank=True, max_length=150, null=True)),
                ('degree_name', models.CharField(blank=True, max_length=150, null=True)),
                ('join_year', models.IntegerField(blank=True, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('hostel', models.CharField(blank=True, max_length=150, null=True)),
                ('hostel_name', models.CharField(blank=True, max_length=150, null=True)),
                ('room', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('key', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ldapPrinting.user')),
            ],
        ),
    ]
